[package]
name = "overdrivectl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cvt-utils = { version = "0.1.0", path = "../cvt-utils" }
x11 = { version = "2.21.0", features = ["xrandr"] }
